//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SeekerTable
    {
        public int SeekerID { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public int CityID { get; set; }
        public int BloodGroupID { get; set; }
        [RegularExpression(@"^01[3-9]\d{8}$", ErrorMessage = "Pleaser enter valid Mobile Number")]
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public int GenderID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int UserID { get; set; }
        public string Address { get; set; }
    
        public virtual BloodGroupTable BloodGroupTable { get; set; }
        public virtual CityTable CityTable { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
